[tool.poetry]
name = "push2d-simulator"
version = "0.1.0"
description = ""
authors = ["nomutin <nomura0508@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
numpy = "^1.24.2"
pygame = "^2.3.0"
pymunk = "^6.4.0"
omegaconf = "^2.3.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
pyproject-flake8 = "^6.0.0.post1"
autopep8 = "^2.0.2"

[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.flake8]
extend-ignore = "E203,"
max-complexity = 8
max-line-length = 79
exclude =["__pycache__",  ".venv"]

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79
