[tool.poetry]
name = "push2d-simulator"
version = "0.1.0"
description = ""
authors = ["nomutin <nomura0508@icloud.com>"]
readme = "README.md"
packages = [{include = "push2d_simulator"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
numpy = "^1.24.2"
pygame = "^2.3.0"
pymunk = "^6.4.0"
omegaconf = "^2.3.0"

[tool.poetry.group.lint]
optional = true
[tool.poetry.group.lint.dependencies]
isort = "^5.12.0"
black = "^23.3.0"
ruff = "^0.0.280"
mypy = "^1.4.1"

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79

[tool.ruff]
select = ["ALL"]
ignore = ["D203", "D212", "ANN", "S311"]
fixable = ["ALL"]
unfixable = []
exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv",]
line-length = 79
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py38"

[tool.mypy]
python_version = 3.9
