[tool.poetry]
name = "push2d-simulator"
version = "0.1.0"
description = ""
authors = ["nomutin <nomura0508@icloud.com>"]
readme = "README.md"
packages = [
    { include = "*", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.2"
pymunk = "^6.4.0"
pygame = "^2.3.0"
hydra-core = "^1.3.2"
natsort = "^8.3.1"

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.2"
pyproject-flake8 = "^6.0.0.post1"
isort = "^5.12.0"
black = "^23.3.0"
mypy = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.flake8]
extend-ignore = "E203,"
max-complexity = 8
max-line-length = 79
exclude =["__pycache__",  ".venv"]

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79

[tool.mypy]
python_version = 3.9
check_untyped_defs = true
disallow_any_decorated = false
disallow_any_generics = false
disallow_any_unimported = false
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_errors = false
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_untyped_calls = true
warn_return_any = true
