space:
  _target_: push_2d.space.Space
  width: 225
  height: 225
  fps: 15
  color: white

agent:
  _target_: push_2d.agent.CircleAgent
  radius: 15
  x_position: 112
  y_position: 205
  velocity: 100
  color: blue

components:
  -
    _target_: push_2d.component.dynamic.Circle
    radius: 30
    x_position: 190
    y_position: 100
    color: red
  -
    _target_: push_2d.component.dynamic.DynamicBox
    radius: 45
    x_position: 100
    y_position: 100
    color: black
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: 0
    x_end_position: ${space.width}
    y_end_position: 0
    color: ${space.color}
    radius: 1
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: 0
    x_end_position: 0
    y_end_position: ${space.height}
    color: ${space.color}
    radius: 1
  -
    _target_: push_2d.component.static.Segment
    x_start_position: ${space.width}
    y_start_position: 0
    x_end_position: ${space.width}
    y_end_position: ${space.height}
    color: ${space.color}
    radius: 1
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: ${space.height}
    x_end_position: ${space.width}
    y_end_position: ${space.height}
    color: ${space.color}
    radius: 1

