space_size: 100

space:
  _target_: push_2d.space.button.ButtonSpace
  width: ${space_size}
  height: ${space_size}
  fps: 15
  color: white
  light_size: 20
  buttons:
    -
      _target_: push_2d.space.button.Button
      x: 0
      y: 20
      radius: 20
      color: red

agent:
  _target_: push_2d.component.agent.CircleAgent
  radius: 10
  x_position: 50
  y_position: 85
  velocity: 100
  color: black

components:
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 10
    y_start_position: 20
    x_end_position: 0
    y_end_position: 30
    color: red
    radius: 2
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: 20
    x_end_position: ${space_size}
    y_end_position: 20
    color: black
    radius: 2
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: 20
    x_end_position: 0
    y_end_position: ${space_size}
    color: black
    radius: 2
  -
    _target_: push_2d.component.static.Segment
    x_start_position: ${space_size}
    y_start_position: 20
    x_end_position: ${space_size}
    y_end_position: ${space_size}
    color: black
    radius: 2
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: ${space_size}
    x_end_position: ${space_size}
    y_end_position: ${space_size}
    color: black
    radius: 2
  -
    _target_: push_2d.component.static.Segment
    x_start_position: 0
    y_start_position: 20
    x_end_position: ${space_size}
    y_end_position: 20
    color: black
    radius: 2
