space:
  _target_: push_2d.component.Space
  width: 300
  height: 300
  fps: 15
  color:
    _target_: pygame.Color
    _args_:
      - white

agent:
  _target_: push_2d.component.Agent
  radius: 20
  position:
    _target_: pymunk.Vec2d
    x: 50
    y: 50
  velocity: 100
  color:
    _target_: pygame.Color
    _args_:
      - blue

obstacles:
  -
    _target_: push_2d.component.Circle
    radius: 30
    position:
      _target_: pymunk.Vec2d
      x: 50
      y: 50
    color: 
      _target_: pygame.Color
      _args_:
        - red
  -
    _target_: push_2d.component.Circle
    radius: 30
    position:
      _target_: pymunk.Vec2d
      x: 250
      y: 175
    color:
      _target_: pygame.Color
      _args_:
        - green

segments:
  -
    _target_: push_2d.component.Wall
    start_x: 0
    start_y: 1
    end_x: ${space.width}
    end_y: 1 
    radius: 10
    color: ${space.color}
  -
    _target_: push_2d.component.Wall
    start_x: 1
    start_y: 0
    end_x: 1
    end_y: ${space.height}
    radius: 10
    color: ${space.color}
  -
    _target_: push_2d.component.Wall
    start_x: ${space.width}
    start_y: 0
    end_x: ${space.width}
    end_y: ${space.height}
    radius: 10
    color: ${space.color}
  -
    _target_: push_2d.component.Wall
    start_x: 0
    start_y: ${space.height}
    end_x: ${space.width}
    end_y: ${space.height}
    radius: 10
    color: ${space.color}
