space:
  _target_: push_2d.component.Space
  width: 300
  height: 225
  fps: 15
  color:
    _target_: pygame.Color
    _args_:
      - white

agent:
  _target_: push_2d.component.Agent
  radius: 20
  position:
    _target_: pymunk.Vec2d
    x: 150
    y: 110
  velocity: 100
  color:
    _target_: pygame.Color
    _args_:
      - blue

obstacles:
  -
    _target_: push_2d.component.Circle
    radius: 30
    position:
      _target_: pymunk.Vec2d
      x: 50
      y: 50
    color: 
      _target_: pygame.Color
      _args_:
        - red
  -
    _target_: push_2d.component.Circle
    radius: 30
    position:
      _target_: pymunk.Vec2d
      x: 250
      y: 175
    color:
      _target_: pygame.Color
      _args_:
        - green

segments:
  -
    _target_: push_2d.component.Segment
    start_position:
      _target_: pymunk.Vec2d
      x: 0
      y: 1
    end_position:
      _target_: pymunk.Vec2d
      x: ${space.width}
      y: 1
    radius: 10
    color: ${space.color}
  -
    _target_: push_2d.component.Segment
    start_position:
      _target_: pymunk.Vec2d
      x: 1
      y: 0
    end_position:
      _target_: pymunk.Vec2d
      x: 1
      y: ${space.height}
    radius: 10
    color: ${space.color}
  -
    _target_: push_2d.component.Segment
    start_position:
      _target_: pymunk.Vec2d
      x: ${space.width}
      y: 0
    end_position:
      _target_: pymunk.Vec2d
      x: ${space.width}
      y: ${space.height}
    radius: 10
    color: ${space.color}
  -
    _target_: push_2d.component.Segment
    start_position:
      _target_: pymunk.Vec2d
      x: 0
      y: ${space.height}
    end_position:
      _target_: pymunk.Vec2d
      x: ${space.width}
      y: ${space.height}
    radius: 10
    color: ${space.color}
