screen:
    width: 300
    height: 240
    fps: 60
    color: white

tracker:
    radius: 10
    color: blue
    velocity: 100
    position:
        - 150
        - 120

objects:
    - 
        radius: 30
        color: red
        position:
            - 50
            - 50
    - 
        radius: 30
        color: green
        position:
            - 200
            - 180

save:
    fps: 5
    length: 40

