name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.lock

    - name: Run black
      run: |
        black . --check

    - name: Run mypy
      run: |
        mypy .

    - name: Run isort
      run: |
        isort . --check-only
    
    - name: Run ruff
      run: |
        ruff .
